source 'https://rubygems.org'

gem 'bundler'
gem 'rake'
gem 'rack-test'
gem 'rack-cache'
gem 'dalli'
gem "sinatra", "~> 1.4.3", require: 'sinatra/base'
gem "sinatra-contrib", github: 'sinatra/sinatra-contrib'
gem 'sinatra-router'
gem 'rspec'
gem 'pry'
gem 'activerecord'
gem 'dotenv'
gem 'pg'
gem 'database_cleaner'
gem 'kaminari'